name: Deploy NestJS to Google Cloud Run

on:
  push:
    branches:
      - dev

env:
  GCP_REGION: asia-southeast1 # Thay bằng region của bạn
  ARTIFACT_REGISTRY_REPO: nestjs-services # Tên repository trên Artifact Registry
  CLOUD_RUN_SERVICE: support-it-api # Tên service bạn muốn đặt trên Cloud Run

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        id: auth
        uses: 'google-github-actions/auth@v2'
        with:
          workload_identity_provider: '${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}'
          service_account: '${{ secrets.GCP_SERVICE_ACCOUNT }}'
      - name: Verify Auth Output
        run: |
          echo "Auth output project_id: ${{ steps.auth.outputs.project_id }}"
          echo "Auth output service_account_email: ${{ steps.auth.outputs.service_account_email }}"
          echo "Auth output access_token: ${{ steps.auth.outputs.access_token }}" # Cẩn thận với access_token, nó nhạy cảm
          # Có thể ${{ steps.auth.outputs.id_token }} là cái chúng ta cần kiểm tra
          echo "Auth output id_token: ${{ steps.auth.outputs.id_token }}"
          # Không nên in ra toàn bộ token trong log công khai, chỉ để debug.
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Configure Docker
        run: gcloud auth configure-docker ${{ env.GCP_REGION }}-docker.pkg.dev

      - name: Build and Push Docker Image
        env:
          IMAGE_URL: ${{ env.GCP_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${{ env.ARTIFACT_REGISTRY_REPO }}/${{ env.CLOUD_RUN_SERVICE }}:${{ github.sha }}
        run: |
          docker build -t $IMAGE_URL -f services/api-service/Dockerfile services/api-service
          docker push $IMAGE_URL

      - name: Deploy to Cloud Run
        env:
          IMAGE_URL: ${{ env.GCP_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${{ env.ARTIFACT_REGISTRY_REPO }}/${{ env.CLOUD_RUN_SERVICE }}:${{ github.sha }}
        run: |
          gcloud run deploy ${{ env.CLOUD_RUN_SERVICE }} \
            --image $IMAGE_URL \
            --platform managed \
            --region ${{ env.GCP_REGION }} \
            --allow-unauthenticated \
            --port 3000